Repository tensorflow/swift-apis, pull requests merged in 2019-06, with the labels that each got.

#221 Adding poisson loss
  Sources/TensorFlow/Loss.swift
  Tests/TensorFlowTests/LossTests.swift
Labels: kokoro:run

#200 Conform `Tensor` to `ElementaryFunctions`.
  Sources/TensorFlow/Initializers.swift
  Sources/TensorFlow/Operators/Math.swift
  Sources/TensorFlow/Operators/NN.swift
Labels: enhancement, kokoro:run

#263 Tensor documentation update. (#TF-448)
  Sources/TensorFlow/Core/Tensor.swift
Labels: kokoro:run

#271 Made 'Tensor.gathering(where:alongAxis:)' differentiable.
  Sources/TensorFlow/Operators/Basic.swift
Labels: enhancement

#149 Added support for 'isFinite', 'isInfinite', and 'isNaN'.
  Tests/TensorFlowTests/OperatorTests/MathTests.swift
Labels: enhancement, kokoro:run

#272 Makes 'Tensor.gathering' generic over 'Int32' and 'Int64'.
  Sources/TensorFlow/Core/DataTypes.swift
  Sources/TensorFlow/Operators/Basic.swift
Labels: enhancement, kokoro:run

#273 Fixed the handling of integer data types in the raw ops generation script.
  Sources/TensorFlow/Bindings/RawOpsGenerated.swift
  Sources/TensorFlow/Bindings/generate_wrappers.py
Labels: enhancement

#277 Added default values to some of the convolution layer initializers.
  Sources/TensorFlow/Layers/Convolutional.swift
Labels: kokoro:run

#150 Added support for 'logSumExp'.
  Sources/TensorFlow/Operators/Math.swift
  Tests/TensorFlowTests/OperatorTests/MathTests.swift
Labels: enhancement, kokoro:run

#147 Added support for the 'log1mexp' op and its VJP.
  Sources/TensorFlow/Operators/Math.swift
  Tests/TensorFlowTests/OperatorTests/MathTests.swift
Labels: enhancement

#266 Convert a LazyTensorTrace into a TFFunction.
  Sources/TensorFlow/Core/LazyTensorTFFunctionBuilder.swift
  Tests/TensorFlowTests/LazyTensorTFFunctionBuilderTests.swift
  Tests/TensorFlowTests/XCTestManifests.swift
Labels: kokoro:run

#293 Turn lazy tensor off in 'tearDown()' in lazy tensor tests.
  Tests/TensorFlowTests/LazyTensorTFFunctionBuilderTests.swift
  Tests/TensorFlowTests/LazyTensorTraceTests.swift
Labels: bug

#295 Eliminate 'assert(false)'
  Sources/TensorFlow/Core/LazyTensorTFFunctionBuilder.swift
Labels: bug

#218 [Optimizer] Simplify optimizers using generalized vector math.
  Sources/TensorFlow/Loss.swift
  Sources/TensorFlow/Operators/Math.swift
  Sources/TensorFlow/Optimizer.swift
  Tests/TensorFlowTests/SequentialTests.swift
  Tests/TensorFlowTests/TrivialModelTests.swift
Labels: enhancement

#314 [Optimizers] Added support for the AMSGrad optimizer.
  Sources/TensorFlow/Optimizers/MomentumBased.swift
  Tests/TensorFlowTests/SequentialTests.swift
Labels: kokoro:run
