Repository tensorflow/swift-apis, pull requests merged in 2019-07, with the labels that each got.

#334 Fix transposed conv2 d initializer
  Sources/TensorFlow/Layers/Convolutional.swift
Labels: bug

#336 [Tensor] Add precondition in 'Tensor.init(arrayLiteral:)' to reject 'init()' calls.
  Sources/TensorFlow/Core/ShapedArray.swift
  Sources/TensorFlow/Core/Tensor.swift
  Tests/TensorFlowTests/TensorTests.swift
Labels: bug

#347 Extend 'Array' and 'Array.DifferentiableView' for aggregate math and collection protocols.
  Sources/TensorFlow/StdlibExtensions.swift
Labels: enhancement

#350 fix _vjpRsqrt and add test
  Sources/TensorFlow/Operators/Math.swift
  Tests/TensorFlowTests/OperatorTests/MathTests.swift
Labels: kokoro:run

#355 Added a test comparing the old batch-norm VJP with the automatically derived one.
  Tests/TensorFlowTests/TensorAutoDiffTests.swift
Labels: kokoro:run

#361 Added support for 'Tensor.clipped(min:max:)' and its VJP.
  Sources/TensorFlow/Operators/Basic.swift
  Sources/TensorFlow/Operators/Math.swift
  Tests/TensorFlowTests/OperatorTests/MathTests.swift
Labels: kokoro:run

#374 Add '.swift-format'.
  .swift-format
Labels: enhancement

#380 Dense layer tests
  Tests/TensorFlowTests/LayerTests.swift
Labels: kokoro:run

#384 use .moments() in LayerNorm and BatchNorm layers
  Sources/TensorFlow/Layers/Normalization.swift
  Tests/TensorFlowTests/LayerTests.swift
Labels: enhancement

#346 Split the `Layer` protocol into `Layer` and `Module` where `Module` does not require `Input: Differentiable`.
  Sources/TensorFlow/Layer.swift
  Sources/TensorFlow/Layers/Convolutional.swift
  Sources/TensorFlow/Layers/Embedding.swift
  Sources/TensorFlow/Layers/Pooling.swift
  Sources/TensorFlow/Layers/Sequential.swift
  Sources/TensorFlow/Layers/Sequential.swift.gyb
  Tests/TensorFlowTests/LayerTests.swift
Labels: enhancement
